name: Promote to live

on:
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: checkout-local
      uses: actions/checkout@v4

    - run: printenv

    - name: Generate a token
      id: generate-token
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ vars.CHILLEDAUTOMATION_ID }}
        private-key: ${{ secrets.CHILLEDGHAUTOMATION }}
        owner: ChilledEther

    - name: git-setup
      run: |
        echo "Setting git config"
        gh auth setup-git
        git config --global push.autoSetupRemote true
        git config --global user.name 'chilledghautomation[bot]'
        git config --global user.email '1130425+chilledghautomation[bot]@users.noreply.github.com'
      env:
        GH_TOKEN: ${{ steps.generate-token.outputs.token }}

    - name: make-live
      shell: pwsh
      run: |
        $stagingDirectory = (Get-Location).Path

        Write-Output "Creating temporary repo directory"
        mkdir ~/repos
        cd ~/repos

        Write-Output "Cloning live repo"
        $productionGit = 'https://github.com/ChilledEther/west-country-leders.git'
        git clone $productionGit
        cd ./west-country-leders

        $date = Get-Date -Format yyyy-MM-dd_HH:mm:ss

        Try {
          Write-Output "Cleaning production"
          $exclusions = @(
            'robots.txt'
            'sitemap.xml'
            'CNAME'
            '.nojekyll'
          )
          Get-ChildItem -Path ./ -Recurse -Exclude $exclusions | Remove-Item -Recurse

          Write-Output "Copying across staging artifacts"
          Get-ChildItem -Path $stagingDirectory -Force | Where-Object { $_.Name -notmatch "^\.(git|github)$" } | Copy-Item -Destination ./ -Recurse -Force

          git remote set-url origin $productionGit
          git remote --verbose
          git status

          git add .
          git commit -m "release: make-live $date"
          git push
        }
        Catch { throw "Issue with adding git" }
      env:
        GH_TOKEN: ${{ steps.generate-token.outputs.token }}